### PR TITLE
Add CITATION.cff

### PR DESCRIPTION
**Pull request by MattF-NSIDC**
@mmacferrin could use your input on this one:

* What contact information would you like associated with this citation? Name + email
* Can you think of other "keywords" for the citation?
* Is there a website URL (aside from this source repository) you'd like to associate with the citation object?
* Do you have a personal website URL you'd like to associate with your author entry in this citation?
* Was this work funded by any grants(s)? If so, can you provide the grant number(s) and institution name(s)?

Thanks :)

### CODE REVIEW

**Comment by mmacferrin** [comment]
- Name + email is fine. michael.macferrin@colorado.edu
- Keywords: umm, these are what I come up with off the top of my head, I think: "Antarctica Today", "Antarctica", "Antarctic", "Melt", "Passive Microwave". Not sure what else might be appropriate.
- URL: None yet. Obviously, the NSIDC public-facing website once it's up & running.
- No personal URL, no.
- Grants: Oooh, crap. I'd need to ping Ted S about that. He scrounged the original funding that paid me to create the code-base, I'd have to ask him what the agencies + grant #s were on those.

**Comment by mmacferrin** [comment]
Edit: The personal URL, just go ahead and link to my OrcID: https://orcid.org/0000-0001-8157-7159

**Comment by MattF-NSIDC** [comment]
Great, thank you Mike! I'll get that information populated, and we can fill in the grant info later. When you have it, can you please add it to #4 ?

**Comment by mmacferrin** [comment]
Yes I see it, will do.

**Review by mmacferrin — COMMENTED** [review]
This looks good to me! Obviously add other contributors on there as applicable down the line. And now that you've created a v1.0.0 DOI, go ahead and add it to the commented-out "doi:" field as well (line 8), if I understand that correctly. Thank you @MattF-NSIDC!

**Comment by MattF-NSIDC** [comment]
>And now that you've created a v1.0.0 DOI, go ahead and add it to the commented-out "doi:" field as well (line 8), if I understand that correctly

I told myself I wouldn't forget, and then I did :P

**Comment by MattF-NSIDC** [comment]
Committed to main: 986b59c

**Pull request merged**
