### PR TITLE
Initialize basic doc structure

### PR DESCRIPTION
**Pull request by MattF-NSIDC**
We have a new `doc/` directory. `repo_structure.md` contains data moved from `README.md` as well as new information about this change.

## PR checklist

- [x] Has a descriptive title
- [x] Has a descriptive body
- [x] Passes checks (to auto-fix a pre-commit.ci failure, add a comment
      containing "pre-commit.ci autofix")

### CODE REVIEW

**Review by mmacferrin — APPROVED** [review]
All looks good to me. Thanks for tagging me on this one. I see no issues here.

**Comment by MattF-NSIDC** [comment]
Any time! Please let me know if the notifications are getting too spammy, happy to tag you on less stuff if so.

**Comment by mmacferrin** [comment]
> Any time! Please let me know if the notifications are getting too spammy, happy to tag you on less stuff if so.

No worries, I likely won't always respond immediately (especially if I'm quite busy), or even at all if I'm getting behind on other stuff. But do let me know if there is anything that requires my input or if you're unsure whether a change might cause unforeseen issues.

**Comment by MattF-NSIDC** [comment]
Will do, I'll `@` you if there's anything I feel needs your eyes, and otherwise will keep adding you as reviewer so you can keep abreast of the changes at your preferred pace.

**Pull request merged**
