### PR TITLE
Remove utf-8 encoding declarations

### PR DESCRIPTION
**Pull request by MattF-NSIDC**
`utf-8` is the default encoding for Python 3, so we don't need these anymore :)

## PR checklist

- [x] Has a descriptive title
- [x] Has a descriptive body
- [x] Passes checks (to auto-fix a pre-commit.ci failure, add a comment
      containing "pre-commit.ci autofix")

### CODE REVIEW

**Comment by mmacferrin** [comment]
Works for me! When reading input from the stdout of other processes, which weren't utf-8 included, I was having issues if I didn't designate that conversion. You can test it runtime and see. If it works for you without those, feel free to remove them.

**Comment by MattF-NSIDC** [comment]
:+1: Thanks Mike, sounds like a good plan. I'll test, and if it becomes a problem later on for any reason, we can always `git revert 33c4d6602addb0cbd27ab3fe51e8088a008c6850` :)

**Comment by mmacferrin** [comment]
Er, wait, I should have looked more closely at the actual changes. Yes, the "utf-8" encoding tags in the header comments of each python file were auto-added by Spyder at the time I made them, which was the environment I was using at the time, so I just left them there. Those can be removed without issue, it won't cause any errors at all. In my previous comment I was thinking you were referring to places in the code I was reading from the stdout of subprocesses, which did require that I do a utf-8 conversion from stdout. But you're not referring to that and this is different. Indeed, no further comment from me, go ahead and remove all those tags.

**Comment by mmacferrin** [comment]
Not sure I should have closed that issue. Feel free to merge the changes.

**Comment by MattF-NSIDC** [comment]
>In my previous comment I was thinking you were referring to places in the code I was reading from the stdout of subprocesses, which did require that I do a utf-8 conversion from stdout.

This makes sense, I was a little bit confused about how it could affect run-time behavior :)

**Pull request merged**
